[project]
name = "ncalab"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "absl-py==2.1.0",
    "albucore==0.0.23",
    "albumentations==2.0.5",
    "annotated-types==0.7.0",
    "asttokens==3.0.0",
    "astunparse==1.6.3",
    "certifi==2024.8.30",
    "charset-normalizer==3.4.0",
    "click==8.1.7",
    "comm==0.2.2",
    "contourpy==1.3.0",
    "cycler==0.12.1",
    "debugpy==1.8.11",
    "decorator==5.1.1",
    "efficientnet-pytorch==0.7.1",
    "efficientnet==1.0.0",
    "numpy==2.0.2",
    "torch==2.7.0",
    "tqdm==4.66.6",
    "emoji==2.14.0",
    "etils==1.12.2",
    "eval-type-backport==0.2.0",
    "executing==2.1.0",
    "filelock==3.16.1",
    "fire==0.7.0",
    "flatbuffers==24.12.23",
    "fonttools==4.54.1",
    "fsspec==2024.10.0",
    "gast==0.6.0",
    "google-pasta==0.2.0",
    "grpcio==1.67.1",
    "gviz-api==1.10.0",
    "h5py==3.12.1",
    "huggingface-hub==0.26.2",
    "idna==3.10",
    "image-classifiers==1.0.0",
    "imageio==2.36.0",
    "importlib-resources==6.5.2",
    "iniconfig==2.0.0",
    "ipykernel==6.29.5",
    "ipython==8.31.0",
    "jedi==0.19.2",
    "jinja2==3.1.4",
    "joblib==1.4.2",
    "jupyter-client==8.6.3",
    "jupyter-core==5.7.2",
    "keras==3.8.0",
    "keras-applications==1.0.8",
    "kiwisolver==1.4.7",
    "lazy-loader==0.4",
    "libclang==18.1.1",
    "markdown==3.7",
    "markdown-it-py==3.0.0",
    "markupsafe==3.0.2",
    "matplotlib==3.9.2",
    "matplotlib-inline==0.1.7",
    "mdurl==0.1.2",
    "medmnist==3.0.2",
    "ml-dtypes==0.4.1",
    "mpmath==1.3.0",
    "munch==4.0.0",
    "mypy==1.13.0",
    "mypy-extensions==1.0.0",
    "namex==0.0.8",
    "nest-asyncio==1.6.0",
    "networkx==3.4.2",
    "onnx==1.17.0",
    "onnxscript==0.2.3",
    "opencv-python-headless==4.10.0.84",
    "opt-einsum==3.4.0",
    "optree==0.13.1",
    "packaging==24.1",
    "pandas==2.2.3",
    "pandas-stubs==2.2.3.241126",
    "parso==0.8.4",
    "pexpect==4.9.0",
    "pillow==11.0.0",
    "pilmoji",
    "platformdirs==4.3.6",
    "pluggy==1.5.0",
    "pretrainedmodels==0.7.4",
    "prompt-toolkit==3.0.48",
    "protobuf==4.25.6",
    "psutil==6.1.1",
    "ptyprocess==0.7.0",
    "pure-eval==0.2.3",
    "pydantic==2.9.2",
    "pydantic-core==2.23.4",
    "pygments==2.19.1",
    "pyparsing==3.2.0",
    "pytest==8.3.3",
    "python-dateutil==2.9.0.post0",
    "pytorch-msssim==1.0.0",
    "pytz==2024.2",
    "pyyaml==6.0.2",
    "pyzmq==26.2.0",
    "regex==2024.11.6",
    "requests==2.32.3",
    "rich==13.9.4",
    "safetensors==0.4.5",
    "scikit-image==0.24.0",
    "scikit-learn==1.5.2",
    "scipy==1.14.1",
    "seaborn==0.13.2",
    "segmentation-models==1.0.1",
    "segmentation-models-pytorch==0.3.4",
    "semver==3.0.4",
    "setuptools==75.3.0",
    "simsimd==6.0.1",
    "six==1.16.0",
    "stack-data==0.6.3",
    "stringzilla==3.10.7",
    "sympy==1.13.3",
    "tensorboard==2.18.0",
    "tensorboard-data-server==0.7.2",
    "tensorboard-plugin-profile==2.19.0",
    "tensorflow==2.18.0",
    "termcolor==2.5.0",
    "threadpoolctl==3.5.0",
    "tifffile==2024.9.20",
    "timm==0.9.7",
    "tokenizers==0.21.0",
    "torch-tb-profiler==0.4.3",
    "torcheval==0.0.7",
    "torchvision==0.22",
    "tornado==6.4.2",
    "traitlets==5.14.3",
    "transformers==4.47.0",
    "triton==3.3.0",
    "types-pytz==2024.2.0.20241003",
    "types-requests==2.32.0.20241016",
    "types-tqdm==4.66.0.20240417",
    "typing-extensions==4.12.2",
    "tzdata==2024.2",
    "urllib3==2.2.3",
    "wcwidth==0.2.13",
    "werkzeug==3.1.2",
    "wheel==0.45.1",
    "wrapt==1.17.1",
    "zipp==3.21.0",
    "sphinx-autoapi>=3.6.0",
]

[tool.uv.sources]
pilmoji = { git = "https://github.com/jay3332/pilmoji", rev = "b4cf625ca37717f93c5c39ed537b2c6fc60c6e13" }
